In [1]:
import torch

In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.2638, 0.3116, 0.8970],
        [0.9697, 0.8787, 0.3464],
        [0.1207, 0.9994, 0.8744],
        [0.9593, 0.8532, 0.1355],
        [0.5581, 0.6917, 0.3145]])


In [4]:
x = torch.empty(5, 3)
print(x)

tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00, -2.4845e-29]])


In [5]:
x = torch.empty(5, 3, dtype = torch.long)
print(x)

tensor([[31244147623002222, 25896114475761774, 32370129135075429],
        [29555336415412316, 30399692628492398, 32370017465139305],
        [12666807751278697, 30118247716159600, 32370056120172641],
        [31244212048494684, 26740621011058797, 30399774233395316],
        [25896196080468075, 32088624093200499, 32651599816097908]])


In [8]:
x = torch.zeros(5, 3, dtype = torch.int)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)


In [9]:
# 创建张量
x = torch.tensor([5, 3])
print(x)

tensor([5, 3])


In [10]:
x = x.new_ones(5, 3, dtype = torch.double)
print(x)
x = torch.randn_like(x, dtype = torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.0468, -0.9178,  1.6719],
        [-1.4244, -0.0846, -1.8017],
        [ 1.0461, -1.1064,  1.1012],
        [-0.6666,  0.0573,  1.1604],
        [ 0.8315, -1.1735, -0.7207]])


In [11]:
print(x.size())  # 获得一个元组

torch.Size([5, 3])


In [16]:
# 加法
y = torch.randn(5, 3)
print(x+y)
print(torch.add(x, y))
result = torch.empty(5,3)
torch.add(x, y, out = result)
print(result)
# in place 加法
y.add_(x)
print(y)

tensor([[ 1.0174, -1.9435, -0.6291],
        [-0.2296, -0.0181, -2.8150],
        [ 1.1150, -0.5916,  1.9517],
        [-1.7134,  0.7695,  1.6056],
        [ 2.5827, -3.3902, -1.3257]])
tensor([[ 1.0174, -1.9435, -0.6291],
        [-0.2296, -0.0181, -2.8150],
        [ 1.1150, -0.5916,  1.9517],
        [-1.7134,  0.7695,  1.6056],
        [ 2.5827, -3.3902, -1.3257]])
tensor([[ 1.0174, -1.9435, -0.6291],
        [-0.2296, -0.0181, -2.8150],
        [ 1.1150, -0.5916,  1.9517],
        [-1.7134,  0.7695,  1.6056],
        [ 2.5827, -3.3902, -1.3257]])
tensor([[ 1.0174, -1.9435, -0.6291],
        [-0.2296, -0.0181, -2.8150],
        [ 1.1150, -0.5916,  1.9517],
        [-1.7134,  0.7695,  1.6056],
        [ 2.5827, -3.3902, -1.3257]])


In [17]:
# 切片+取值
print(x)
print(x[:1])

tensor([[-0.0468, -0.9178,  1.6719],
        [-1.4244, -0.0846, -1.8017],
        [ 1.0461, -1.1064,  1.1012],
        [-0.6666,  0.0573,  1.1604],
        [ 0.8315, -1.1735, -0.7207]])
tensor([[-0.0468, -0.9178,  1.6719]])


In [18]:
# 改变大小
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # -1代表不给出维度直接推断出来
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [19]:
#　使用.item()从tensor中获取value
print(x)
print(x.item())

tensor([[ 0.6656, -0.6101, -0.8932,  1.1866],
        [-1.0830, -1.6736, -0.2389, -1.2260],
        [-0.2945, -0.0823,  1.0117, -1.1041],
        [ 0.4991, -1.0487, -0.7827, -0.3319]])


ValueError: only one element tensors can be converted to Python scalars

In [21]:
#　使用.item()从tensor中获取value
x = torch.randn(1)
print(x)
print(x.item())

tensor([1.8268])
1.8267745971679688


### 自动微分

In [23]:
x = torch.ones(2, 2, requires_grad = True)
print(x)
y = x + 2
print(y)
# y有gran_fn
print(y.grad_fn)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [25]:
print(y * y)
z = y * y * 3
out = z.mean()  # 计算每一行的平均数
print(z, out)

tensor([[9., 9.],
        [9., 9.]], grad_fn=<MulBackward0>)
tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [29]:
a = torch.randn(2, 2)
print(a.requires_grad)
a.requires_grad = True
print(a.requires_grad)
print('-------')
b = torch.randn(2, 2, requires_grad = True)
print(b.requires_grad)
print(b.grad_fn)
b = a * a
print(b.grad_fn)
b = b.mean()
print(b.grad_fn)

False
True
-------
True
None


In [30]:
print(x)
print(x.grad)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
None


In [32]:
x = torch.randn(3, requires_grad = True)
y = x * 2
print(x)
print(y)
while y.data.norm() < 1000:
    y = y * 2
print(y)

tensor([0.7901, 0.0923, 1.1067], requires_grad=True)
tensor([1.5801, 0.1847, 2.2134], grad_fn=<MulBackward0>)
tensor([ 809.0308,   94.5475, 1133.2550], grad_fn=<MulBackward0>)


In [33]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype = torch.float)
y.backward(v)
print(x.grad)

tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])


In [34]:
print(x.requires_grad)
print((x ** 2).requires_grad)
with torch.no_grad():
    print((x ** 2).requires_grad)

True
True
False


In [35]:
# Pytorch神经网络
'''
一个典型的神经网络训练过程包括以下几点：
1.定义一个包含可训练参数的神经网络
2.迭代整个输入
3.通过神经网络处理输入
4.计算损失(loss)
5.反向传播梯度到神经网络的参数
6.更新网络的参数，典型的用一个简单的更新方法：weight = weight - learning_rate *gradient
'''

'\n一个典型的神经网络训练过程包括以下几点：\n1.定义一个包含可训练参数的神经网络\n2.迭代整个输入\n3.通过神经网络处理输入\n4.计算损失(loss)\n5.反向传播梯度到神经网络的参数\n6.更新网络的参数，典型的用一个简单的更新方法：weight\xa0=\xa0weight\xa0-\xa0learning_rate\xa0*gradient\n'